"use client";
import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

export default function TechRing3D() {
    // Load the GLB file generated by Blender
    const { scene } = useGLTF('/models/tech_ring.glb');
    const ringRef = useRef();

    useFrame((state, delta) => {
        if (ringRef.current) {
            // Rotate the ring continuously along Z and slightly along X/Y for parallax
            ringRef.current.rotation.z += delta * 0.2;
            ringRef.current.rotation.x = Math.sin(state.clock.elapsedTime * 0.5) * 0.05;
            ringRef.current.rotation.y = Math.cos(state.clock.elapsedTime * 0.5) * 0.05;
        }
    });

    return (
        <group ref={ringRef} position={[0, 0, -5]}>
            {/* The model uses emissive materials, so we don't strictly need lights, but adding ambient helps */}
            <ambientLight intensity={0.5} />
            <primitive object={scene} scale={2} />
        </group>
    );
}
